name: Ubuntu

on:
  push: 
    branches: [ master ]

jobs:
  ubuntu:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Install
      run: |
        apt-get install zsh
        chmod +x ./install.sh
        ./install.sh
